export { MainFirstSection } from './FirstSection/mainFirstSection';
export { NewsTicker } from './NewsTicker/NewsTicker';
export { CenterColumnFourthSection } from './FourthSectionComponents/CenterColumnFourthSection';
export { default as ArticleCard } from './SecondSection/article-card';
export { default as MainSecondSection } from './SecondSection/mainSecondSection';
export { default as MainThirdSection } from './ThirdSection/mainThirdSection';
export { default as MainFourthSection } from './FourthSection/mainFourthSection';
export { default as MainFifthSection } from './FifthSection/mainFifthSection';
export { default as MainSixthSection } from './SixthSection/MainSixthSection';
export { default as MainSeventhSection } from './SeventhSectionComponents/mainSeventhSection';
