export const EDITORIAL_LIST_SIDEBAR_COUNT = 5;
export const EDITORIAL_LIST_MORE_BATCH_SIZE = 10;
export const EDITORIAL_LIST_HERO_COUNT = 1 + EDITORIAL_LIST_SIDEBAR_COUNT;
export const EDITORIAL_LIST_CONTENT_OFFSET = EDITORIAL_LIST_HERO_COUNT;
/** Hero + first load-more batch (server-rendered). */
export const EDITORIAL_LIST_INITIAL_FETCH_SIZE =
  EDITORIAL_LIST_CONTENT_OFFSET + EDITORIAL_LIST_MORE_BATCH_SIZE;
