export {
  EDITORIAL_LIST_SIDEBAR_COUNT as OPINION_SIDEBAR_COUNT,
  EDITORIAL_LIST_MORE_BATCH_SIZE as OPINION_MORE_BATCH_SIZE,
  EDITORIAL_LIST_HERO_COUNT as OPINION_HERO_COUNT,
  EDITORIAL_LIST_CONTENT_OFFSET as OPINION_CONTENT_OFFSET,
  EDITORIAL_LIST_INITIAL_FETCH_SIZE as OPINION_INITIAL_FETCH_SIZE,
} from "./editorial-list-index-constants";
